apiVersion: v1
kind: Pod
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
  creationTimestamp: null
  labels:
    component: etcd
    tier: control-plane
  name: etcd
  namespace: kube-system
spec:
  containers:
  - command:
    - etcd
    - --listen-client-urls=https://{{PRIVATE_IP}}:2379
    - --advertise-client-urls=https://{{PRIVATE_IP}}:2379
    - --listen-peer-urls=https://{{PRIVATE_IP}}:2380
    - --data-dir=/data/etcd
    - --client-cert-auth=true
    - --peer-client-cert-auth=true
    - --cert-file=/etc/kubernetes/pki/apiserver.crt
    - --key-file=/etc/kubernetes/pki/apiserver.key
    - --peer-cert-file=/etc/kubernetes/pki/apiserver.crt
    - --peer-key-file=/etc/kubernetes/pki/apiserver.key
    - --peer-trusted-ca-file=/etc/kubernetes/pki/apiserver.crt
    - --trusted-ca-file=/etc/kubernetes/pki/apiserver.crt
    - --snapshot-count=10000
    # - --name=etcd1
    # - --initial-advertise-peer-urls=https://{{PRIVATE_IP}}:2380
    # - --initial-cluster=etcd1=https://172.16.71.128:2380
    # - --initial-cluster-state=new
    # - --initial-cluster-token=k8s
    image: k8s.gcr.io/etcd:3.2.24
    livenessProbe:
      exec:
        command:
        - /bin/sh
        - -ec
        - ETCDCTL_API=3 etcdctl --cacert=/etc/kubernetes/pki/ca.crt --endpoints={{PRIVATE_IP}}:2379
          --cert=/etc/kubernetes/pki/apiserver.crt --key=/etc/kubernetes/pki/apiserver.key
          get foo
      failureThreshold: 8
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: etcd
    resources: {}
    volumeMounts:
    - mountPath: /data/etcd
      name: etcd-data
    - mountPath: /etc/kubernetes/pki
      name: etcd-certs
    - name: tz-config
      mountPath: /etc/localtime
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
  - hostPath:
      path: /data/etcd
      type: DirectoryOrCreate
    name: etcd-data
  - hostPath:
      path: /etc/kubernetes/pki
      type: DirectoryOrCreate
    name: etcd-certs
  - name: tz-config
    hostPath:
      path: /usr/share/zoneinfo/Asia/Shanghai
status: {}
